"""
Generic, catalog-driven access to BriefingIQ read-only APIs.

The catalog (data/briefingiq_api_catalog.json, generated by
scripts/build_api_catalog.py from the public OpenAPI specs) lists every
allowlisted GET endpoint. The agent uses a two-step flow:

  1. search_endpoints("vacant slots")   -> candidate endpoints with params
  2. call_endpoint("get_events_eventid_meetinglocations", ...) -> live data

Only endpoints present in the catalog can be called, and the catalog contains
GET operations only, so this tool cannot mutate anything. Auth and tenant
context (Authorization, x-cloud-*) are forwarded from the incoming request
headers, so results respect the caller's own permissions.
"""
import json
import os
import re
import time
from pathlib import Path
from urllib.parse import quote

import requests

from logging_config import get_logger

logger = get_logger(__name__)

CATALOG_PATH = Path(__file__).resolve().parent.parent / "data" / "briefingiq_api_catalog.json"

BASE_URL = os.environ.get(
    "BRIEFINGIQ_API_BASE", "https://briefings.briefingiq.com/events/api"
)

_MAX_RESPONSE_CHARS = 30_000  # keep tool output within LLM context budget

_catalog_cache = None

_RESPONSE_CACHE: dict = {}
_RESPONSE_CACHE_TTL = 120  # seconds, matches briefingiq_api_client


def _load_catalog():
    global _catalog_cache
    if _catalog_cache is None:
        with open(CATALOG_PATH) as f:
            endpoints = json.load(f)["endpoints"]
        _catalog_cache = {e["id"]: e for e in endpoints}
    return _catalog_cache


def _tokenize(text):
    return set(re.findall(r"[a-z0-9]+", text.lower()))


def search_endpoints(query, limit=8):
    """
    Keyword-search the endpoint catalog. Returns the best-matching endpoints
    with their full parameter lists, ready to pass to call_endpoint.
    """
    catalog = _load_catalog()
    query_tokens = _tokenize(query)
    if not query_tokens:
        return []

    scored = []
    for endpoint in catalog.values():
        haystacks = [
            (_tokenize(endpoint["path"]), 3.0),
            (_tokenize(endpoint["tag"]), 2.0),
            (_tokenize(endpoint["summary"]), 1.0),
            (_tokenize(" ".join(p["name"] for p in endpoint["params"])), 0.5),
        ]
        score = 0.0
        for tokens, weight in haystacks:
            # exact token hits plus substring hits (e.g. "location" in "locationhours")
            for qt in query_tokens:
                if qt in tokens:
                    score += weight
                elif any(qt in t for t in tokens):
                    score += weight * 0.5
        if score > 0:
            scored.append((score, endpoint))

    scored.sort(key=lambda item: (-item[0], item[1]["path"]))
    return [
        {
            "id": e["id"],
            "path": e["path"],
            "tag": e["tag"],
            "summary": e["summary"],
            "params": e["params"],
        }
        for _, e in scored[:limit]
    ]


def _build_headers(schedule_headers):
    headers = schedule_headers or {}

    def h(name, default=""):
        return headers.get(name.lower(), headers.get(name, default))

    return {
        "Accept": "application/json, text/plain, */*",
        "Authorization": h("Authorization"),
        "X-Cloud-Categoryid": h("x-cloud-categoryid"),
        "X-Cloud-Categorytypeid": h("x-cloud-categorytypeid", "CATEGORY_TYPE_BRIEFINGS"),
        "X-Cloud-Eventid": h("x-cloud-eventid"),
        "X-Cloud-Client-Timezone": h("x-cloud-client-timezone", "America/Los_Angeles"),
        "X-Cloud-Context-Timezone": h("x-cloud-context-timezone", "America/Los_Angeles"),
        "X-Cloud-Requested-Timezone": h("x-cloud-requested-timezone", "America/Los_Angeles"),
        "X-Cloud-Customerid": h("x-cloud-customerid"),
        "X_cloud_user": h("x_cloud_user"),
    }


def call_endpoint(endpoint_id, path_params=None, query_params=None, schedule_headers=None):
    """
    Execute an allowlisted GET endpoint from the catalog.

    Args:
        endpoint_id: id from search_endpoints (e.g. "get_roledataaccess").
        path_params: dict filling the {placeholders} in the path.
        query_params: dict of query-string parameters.
        schedule_headers: incoming request headers (auth + tenant context).

    Returns:
        Dict with either the (possibly truncated) JSON response or an error.
    """
    catalog = _load_catalog()
    endpoint = catalog.get(endpoint_id)
    if endpoint is None:
        return {
            "error": f"Unknown endpoint_id '{endpoint_id}'. Use search_briefingiq_endpoints first."
        }

    path_params = path_params or {}
    query_params = {k: v for k, v in (query_params or {}).items() if v is not None}

    placeholders = re.findall(r"\{([^{}]+)\}", endpoint["path"])
    missing = [p for p in placeholders if not str(path_params.get(p, "")).strip()]
    if missing:
        return {
            "error": f"Missing required path params {missing} for {endpoint['path']}.",
            "params": endpoint["params"],
        }

    path = endpoint["path"]
    for name in placeholders:
        path = path.replace("{" + name + "}", quote(str(path_params[name]), safe=""))

    url = f"{BASE_URL}{path}"

    cache_key = json.dumps([url, sorted(query_params.items())], default=str)
    cached = _RESPONSE_CACHE.get(cache_key)
    if cached and time.time() - cached[0] < _RESPONSE_CACHE_TTL:
        logger.debug(f"api_catalog cache hit for {url}")
        return cached[1]

    logger.info(f"🌐 call_endpoint {endpoint_id}: GET {url} params={query_params}")
    try:
        response = requests.get(
            url,
            headers=_build_headers(schedule_headers),
            params=query_params or None,
            timeout=30,
        )
    except requests.RequestException as exc:
        return {"error": f"Request failed: {exc}"}

    if response.status_code != 200:
        return {
            "error": f"HTTP {response.status_code} from {endpoint['path']}",
            "body": response.text[:1000],
        }

    try:
        data = response.json()
    except ValueError:
        return {"error": "Non-JSON response", "body": response.text[:1000]}

    result = {"endpoint": endpoint["path"], "data": data}
    if len(json.dumps(result, default=str)) > _MAX_RESPONSE_CHARS:
        result = _truncate_payload(endpoint["path"], data)

    _RESPONSE_CACHE[cache_key] = (time.time(), result)
    return result


def _truncate_payload(endpoint_path, data):
    """Trim oversized responses: shrink embedded lists first, then hard-cut."""
    trimmed = data
    if isinstance(data, dict) and isinstance(data.get("_embedded"), dict):
        embedded = {}
        for key, value in data["_embedded"].items():
            if isinstance(value, list):
                keep = []
                used = 0
                for item in value:
                    used += len(json.dumps(item, default=str))
                    if used > _MAX_RESPONSE_CHARS:
                        break
                    keep.append(item)
                embedded[key] = keep
                embedded[f"{key}_total"] = len(value)
            else:
                embedded[key] = value
        trimmed = {**data, "_embedded": embedded}

    serialized = json.dumps(trimmed, default=str)
    if len(serialized) > _MAX_RESPONSE_CHARS:
        return {
            "endpoint": endpoint_path,
            "truncated": True,
            "data_preview": serialized[:_MAX_RESPONSE_CHARS],
        }
    return {"endpoint": endpoint_path, "truncated": True, "data": trimmed}
